define(function(require) {
	let Test = require("test.js");
	Formulas = require("../src/scripts/Formulas.js");
	Test.table(Formulas.AR, [
		-1,
		0,
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		[0, {
			easy: true,
			noFail: false,
			halfTime: false,
			hardRock: false,
			suddenDeath: false,
			perfect: false,
			doubleTime: false,
			nightCore: false,
			hidden: false,
			flashLight: false,
			relax: false,
			autoPilot: false,
			spunOut: false,
			auto: false,
			cinema: false,
			scoreV2: false,
		}],
		[10, {
			easy: true,
			noFail: false,
			halfTime: false,
			hardRock: false,
			suddenDeath: false,
			perfect: false,
			doubleTime: false,
			nightCore: false,
			hidden: false,
			flashLight: false,
			relax: false,
			autoPilot: false,
			spunOut: false,
			auto: false,
			cinema: false,
			scoreV2: false,
		}],
		[0, {
			easy: false,
			noFail: false,
			halfTime: false,
			hardRock: true,
			suddenDeath: false,
			perfect: false,
			doubleTime: false,
			nightCore: false,
			hidden: false,
			flashLight: false,
			relax: false,
			autoPilot: false,
			spunOut: false,
			auto: false,
			cinema: false,
			scoreV2: false,
		}],
		[5, {
			easy: false,
			noFail: false,
			halfTime: false,
			hardRock: true,
			suddenDeath: false,
			perfect: false,
			doubleTime: false,
			nightCore: false,
			hidden: false,
			flashLight: false,
			relax: false,
			autoPilot: false,
			spunOut: false,
			auto: false,
			cinema: false,
			scoreV2: false,
		}],
		[10, {
			easy: false,
			noFail: false,
			halfTime: false,
			hardRock: true,
			suddenDeath: false,
			perfect: false,
			doubleTime: false,
			nightCore: false,
			hidden: false,
			flashLight: false,
			relax: false,
			autoPilot: false,
			spunOut: false,
			auto: false,
			cinema: false,
			scoreV2: false,
		}],
	], [
		1.92,
		1.8,
		1.68,
		1.56,
		1.44,
		1.32,
		1.2,
		1.05,
		0.9,
		0.75,
		0.6,
		0.45,
		0.3,
		Formulas.AR(0),
		Formulas.AR(5),
		Formulas.AR(0),
		Formulas.AR(7),
		Formulas.AR(10),
	]);
});